name = "gleez"
version = "0.3.2"

description = "Elegant, Modern, and Customizable TailwindCSS components for âœ¨ Lustre âœ¨ "
licences = ["MIT"]
repository = { type = "github", user = "MAHcodes", repo = "gleez" }
links = [{ title = "Website", href = "https://gleez.netlify.app/" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"
gleam_httpc = ">= 2.2.0 and < 5.0.0"
gleam_http = ">= 3.6.0 and < 4.0.0"
simplifile = ">= 1.7.0 and < 3.0.0"
argv = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
